[2025-02-01T07:37:03.156+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T07:37:03.184+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T07:37:03.413+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2025-01-31T00:00:00+00:00 [queued]>
[2025-02-01T07:37:03.414+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T07:37:03.466+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2025-01-31 00:00:00+00:00
[2025-02-01T07:37:03.484+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=126) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T07:37:03.487+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2025-02-01T07:37:03.488+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-01-31T00:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpddcgk6wa']
[2025-02-01T07:37:03.489+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask inaccurate
[2025-02-01T07:37:03.560+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-01-31T00:00:00+00:00 [running]> on host f20f83373f6a
[2025-02-01T07:37:03.701+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T00:00:00+00:00'
[2025-02-01T07:37:03.705+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-01T07:37:03.708+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-01T07:37:03.709+0000] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2025-02-01 07:37:03.185201+00:00
[2025-02-01T07:37:03.710+0000] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-02-01T07:37:03.711+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T07:37:03.712+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-01T07:37:03.726+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2025-02-01T07:37:03.746+0000] {subprocess.py:99} INFO - Output:
[2025-02-01T07:37:03.754+0000] {subprocess.py:106} INFO - inaccurate
[2025-02-01T07:37:03.755+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-01T07:37:03.802+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T07:37:03.804+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=scheduled__2025-01-31T00:00:00+00:00, execution_date=20250131T000000, start_date=20250201T073703, end_date=20250201T073703
[2025-02-01T07:37:03.826+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-01T07:37:03.828+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-01T07:37:03.829+0000] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-02-01 07:36:43.935385+00:00
[2025-02-01T07:37:03.830+0000] {logging_mixin.py:190} INFO - Task hostname:f20f83373f6a operator:BashOperator
[2025-02-01T07:37:03.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T07:37:03.892+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T07:37:03.895+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
