[2025-01-24T02:06:16.778+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T02:06:16.804+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T02:06:16.939+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2025-01-23T00:00:00+00:00 [queued]>
[2025-01-24T02:06:16.940+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-24T02:06:16.958+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2025-01-23 00:00:00+00:00
[2025-01-24T02:06:16.976+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=8535) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-24T02:06:16.978+0000] {standard_task_runner.py:72} INFO - Started process 8537 to run task
[2025-01-24T02:06:16.978+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2025-01-23T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpw8pp7j2l']
[2025-01-24T02:06:16.980+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask inaccurate
[2025-01-24T02:06:17.055+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2025-01-23T00:00:00+00:00 [running]> on host f20f83373f6a
[2025-01-24T02:06:17.152+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2025-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-23T00:00:00+00:00'
[2025-01-24T02:06:17.154+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-24T02:06:17.155+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-24T02:06:17.156+0000] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2025-01-24 02:06:16.805576+00:00
[2025-01-24T02:06:17.157+0000] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-01-24T02:06:17.158+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T02:06:17.159+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-24T02:06:17.162+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2025-01-24T02:06:17.182+0000] {subprocess.py:99} INFO - Output:
[2025-01-24T02:06:17.191+0000] {subprocess.py:106} INFO - inaccurate
[2025-01-24T02:06:17.192+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-24T02:06:17.221+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T02:06:17.223+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=scheduled__2025-01-23T00:00:00+00:00, execution_date=20250123T000000, start_date=20250124T020616, end_date=20250124T020617
[2025-01-24T02:06:17.236+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-24T02:06:17.237+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-24T02:06:17.238+0000] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2025-01-24 02:06:04.051979+00:00
[2025-01-24T02:06:17.239+0000] {logging_mixin.py:190} INFO - Task hostname:f20f83373f6a operator:BashOperator
[2025-01-24T02:06:17.277+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T02:06:17.298+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T02:06:17.304+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
